#!/bin/bash

bin_dir=$(dirname $0)
cd ${bin_dir}/..
savant_home=${PWD}
cd - > /dev/null 2>&1

classpath=
for f in $(ls ${savant_home}/lib); do
  classpath=${classpath}:${savant_home}/lib/${f}
done

if [[ $(uname -a | grep -i cygwin) != "" ]]; then
  classpath=$(cygpath -wp ${classpath})
  savant_home=$(cygpath -wa ${savant_home})
fi

java -cp ${classpath} org.savantbuild.runtime.Main $@
