#!/bin/bash

if [ -z "${JAVA_HOME}" ]; then
  echo "The JAVA_HOME environment variable is not set. Please set this to point to a JDK 8 installation of Java such that \$JAVA_HOME/bin/java points to the Java executable"
  exit 1
fi

bin_dir=$(dirname $0)
cd ${bin_dir}/..
home_dir=${PWD}
cd - > /dev/null 2>&1

classpath=
for f in $(ls ${home_dir}/lib); do
  classpath=${classpath}:${home_dir}/lib/${f}
done

if [[ $(uname -a | grep -i cygwin) != "" ]]; then
  classpath=$(cygpath -wp ${classpath})
  home_dir=$(cygpath -wa ${home_dir})
fi

suspend=""
if [[ $# > 1 && $1 == "--suspend" ]]; then
  suspend="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8000"
fi

${JAVA_HOME}/bin/java ${suspend} -cp ${classpath} org.savantbuild.runtime.Main $@
