name: test

# Run the tests when code is pushed to `master`
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Multiple runs, one for each version of Java we support
    strategy:
      matrix:
        javaVersion: [ '1.8', '11', '17' ]

    steps:
      # Java 8 is currently required to run Savant 1.0.0. We must install that but also the other versions we want to test
      # against. This separates the matrix from the Java versions, but it simplifies the Savant configuration setup
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            8
            11
            17
      - name: Install Savant Build
        run: |
          mkdir -p ~/dev/savant
          mkdir -p ~/.savant/plugins
          cd ~/dev/savant
          curl -fSL http://savant.inversoft.org/org/savantbuild/savant-core/1.0.0/savant-1.0.0.tar.gz > savant-1.0.0.tar.gz
          tar -xzf savant-1.0.0.tar.gz
          ln -s savant-1.0.0 current
          rm savant-1.0.0.tar.gz
          cat <<EOF > ~/.savant/plugins/org.savantbuild.plugin.java.properties
          1.8=${JAVA_HOME_8_x64}
          11=${JAVA_HOME_11_x64}
          17=${JAVA_HOME_17_x64}
          EOF
          cat ~/.savant/plugins/org.savantbuild.plugin.java.properties
        shell: bash
      - name: Run the build
        run: |
          export PATH=$PATH:~/dev/savant/current/bin
          sb clean int --debug --javaVersion=${{ matrix.javaVersion }}
        shell: bash
