name: test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  strategy:
    matrix:
      javaVersion: [ '1.8', '11', '17' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy_website"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Java 8 is currently required to run Savant 1.0.0. We must install that but also the other versions we want to test
      # against. This separates the matrix from the Java versions, but it simplifies the Savant configuration setup
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            8
            11
            17
      - name: Install Savant Build
        run: |
          mkdir -p ~/dev/savant
          mkdir -p ~/.savant/plugins
          cd ~/dev/savant
          curl -fSL http://savant.inversoft.org/org/savantbuild/savant-core/1.0.0/savant-1.0.0.tar.gz > savant-1.0.0.tar.gz
          tar -xzf savant-1.0.0.tar.gz
          ln -s savant-1.0.0 current
          rm savant-1.0.0.tar.gz
          cat <<EOF > ~/.savant/plugins/org.savantbuild.plugin.java.properties
          1.8=${JAVA_HOME_8_x64}
          11=${JAVA_HOME_11_x64}
          17=${JAVA_HOME_17_x64}
          EOF
        shell: bash
      - name: Run the build
        run: |
          export PATH=$PATH:~/dev/savant/current/bin
          sb clean int --javaVersion=${{ matrix.javaVersion }}
        shell: bash
